// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7DDdCEzYyuJqUakgIOGHIlen99M-GS90',
    appId: '1:433328034608:web:53af22e702a4449138aef5',
    messagingSenderId: '433328034608',
    projectId: 'icheck-backend',
    authDomain: 'icheck-backend.firebaseapp.com',
    storageBucket: 'icheck-backend.appspot.com',
    measurementId: 'G-PG833XW1XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD66Ctp5_SJY6mxup89B07viLN04yKYynk',
    appId: '1:433328034608:android:e63ad7479e51166038aef5',
    messagingSenderId: '433328034608',
    projectId: 'icheck-backend',
    storageBucket: 'icheck-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP7nypGa44swOSEgDZWyEhxwzVzRVMkqo',
    appId: '1:433328034608:ios:e1a87cdb61f2b6d038aef5',
    messagingSenderId: '433328034608',
    projectId: 'icheck-backend',
    storageBucket: 'icheck-backend.appspot.com',
    iosClientId:
        '433328034608-bqtj81njfs1ffa19kaol7lqhraof0vfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.icheckApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP7nypGa44swOSEgDZWyEhxwzVzRVMkqo',
    appId: '1:433328034608:ios:e1a87cdb61f2b6d038aef5',
    messagingSenderId: '433328034608',
    projectId: 'icheck-backend',
    storageBucket: 'icheck-backend.appspot.com',
    iosClientId:
        '433328034608-bqtj81njfs1ffa19kaol7lqhraof0vfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.icheckApp',
  );
}
